### ISSUE TITLE
Enhance FTBApp download links

### ISSUE THREAD

**Issue by jikuja** [FTBTeam/FTB-Website#3]
## The problem
Current .sh version returns `content-type: text/plain; charset=utf-8` which makes browsers to display content in browser instead of offering saving the file. New linux users are confused about this and try to copy paste content from browser into file and then they have broken installer file.

## Solution
FTBApp download URLs should return `content-type: application/octet-stream`header ass part of the response. Using content-type header is probably one of the easiest way to control client-side behaviour of the .sh download link.

## Other solutions
* `download`attribute in `a` tags: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes but requirement for same origin URL probablty causes problems.

## Quotes from users

> Hey I've been running into a problem where the linux download from your website for the launcher is not working and just sends me to a broken webpage. Any help would be great thanks!

> So what's up with the linux download? I really don't understand how to download it

> (screenshot of the installer script in text editor)
> thats literally the linux version
> when i press download linux(.sh)

> I hope this is the right place to ask. Can't find anything on the forums or faq. Trying to install ftb app on linux, but rather than downloading the .sh, I am taken to a text page. Creating a .sh file from the text gives an "installer file is corrupted" error. Any assistance would be great.

> It just brings me here when I click the download button
> (screensot of the text editor with installer code)

> how do i install the new ftb launcher on Linux
> i keep getting an error saying the installer is corrupt
> i copied and paste the sh code from the browser to a sh file i made but im not sure if thats how your suppose to do it
> it gives me this gzip: sfx_archive.tar.gz: not in gzip format

**Comment by Gaz492** [comment]
Download attribute does not work in this case, will need to have the content-type set for it to be downloadable

**Comment by Jake-E** [comment]
This should be resolved once cache breaks.
